### ISSUE TITLE
Failed to activate the file-bookmark package

### ISSUE THREAD

**Issue by Samuel29** [akalajzi/atom-file-bookmark#10]
[Enter steps to reproduce below:]
1. install file-bookmark package
2. restart Atom

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [file-bookmark](https://github.com/akalajzi/atom-file-bookmark) package, v0.3.1
### Stack Trace

Failed to activate the file-bookmark package

```
At Cannot read property 'split' of undefined

TypeError: Cannot read property 'split' of undefined
    at FileBookmarkView.module.exports.FileBookmarkView._splitPathnameAndFilename (/Users/USER/.atom/packages/file-bookmark/lib/file-bookmark-view.coffee:169:25)
    at FileBookmarkView.module.exports.FileBookmarkView._groupPaths (/Users/USER/.atom/packages/file-bookmark/lib/file-bookmark-view.coffee:154:15)
    at FileBookmarkView.module.exports.FileBookmarkView.renderItems (/Users/USER/.atom/packages/file-bookmark/lib/file-bookmark-view.coffee:87:21)
    at new FileBookmarkView (/Users/USER/.atom/packages/file-bookmark/lib/file-bookmark-view.coffee:80:6)
    at Function.module.exports.FileBookmarkView.deserialize (/Users/USER/.atom/packages/file-bookmark/lib/file-bookmark-view.coffee:12:9)
    at DeserializerManager.module.exports.DeserializerManager.deserialize (/Applications/Atom.app/Contents/Resources/app.asar/src/deserializer-manager.js:45:29)
    at FileBookmark.activate (/Users/USER/.atom/packages/file-bookmark/lib/file-bookmark.coffee:24:46)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:754:28
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.8.3
Sublime-Style-Column-Selection, v1.5.1
atom-ternjs, v0.14.1
compare-files, v0.6.2
file-bookmark, v0.3.1
file-icons, v1.7.14
language-protobuf, v0.5.0
language-r, v0.4.1
language-scala, v1.1.6
linter, v1.11.8
linter-sass-lint, v1.5.0
merge-conflicts, v1.4.4
minimap, v4.24.4
open-recent, v5.0.0
pigments, v0.29.2
project-manager, v2.9.7
tablr, v1.3.1

# Dev
No dev packages
```

**Comment by akalajzi** [comment]
Please update. If problem persists, please reopen and I'll try to put some more time into it. I couldn't reproduce it myself.
